/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientapp;
import java.io.*;
import java.net.*;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class MotherFrame extends javax.swing.JFrame {
        private static boolean temp=false;
        private static Socket s = null;
	private static BufferedReader br = null;
	private static PrintWriter pr = null;
        private static String mother=null;
        public static String get="something";
    /**
     * Creates new form MotherFrame
     */
    public MotherFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginPage = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PassWord = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        SendMessage = new javax.swing.JTextArea();
        To = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.CardLayout());

        loginPage.setMaximumSize(new java.awt.Dimension(800, 600));
        loginPage.setPreferredSize(new java.awt.Dimension(800, 600));
        loginPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        loginPage.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 150, -1));

        jLabel3.setText("UserName :");
        loginPage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 70, 20));

        PassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassWordActionPerformed(evt);
            }
        });
        loginPage.add(PassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 150, -1));

        jLabel4.setText("PassWord :");
        loginPage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 70, 20));

        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginPage.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        loginPage.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue_orb_by_otsboi.png"))); // NOI18N
        loginPage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -6, 790, 610));

        jPanel1.add(loginPage, "card3");

        Profile.setMaximumSize(new java.awt.Dimension(600, 400));
        Profile.setPreferredSize(new java.awt.Dimension(600, 400));

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jScrollPane3.setViewportView(jList3);

        jScrollPane4.setViewportView(jList4);

        SendMessage.setColumns(20);
        SendMessage.setRows(5);
        jScrollPane5.setViewportView(SendMessage);

        To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToActionPerformed(evt);
            }
        });

        jButton3.setText("Send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Send Request");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Accept Request");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Send File");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane6.setViewportView(TextArea);

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addContainerGap(156, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addContainerGap(108, Short.MAX_VALUE)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProfileLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jPanel1.add(Profile, "card2");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void PassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassWordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /* try{        
                         s = new Socket("localhost", 5556);
			br = new BufferedReader(new InputStreamReader(s.getInputStream()));
			pr = new PrintWriter(s.getOutputStream());
        }
        catch(Exception e){e.printStackTrace();}*/
                        String user=UserName.getText();
                        String pass=PassWord.getText();
                        user="log_"+user+"_"+pass;
                        System.out.println(user);
                     try{  // pr.println("log");pr.flush();
                        pr.println(user);pr.flush();
                       // get=br.readLine();
                        //System.out.println(get);
                     }
                     catch(Exception e)
                     {
                         e.printStackTrace();
                     }
                      
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             try
		{
                       
                       
                        String user=UserName.getText();
                        String pass=PassWord.getText();
                        user="sign_"+user+"_"+pass;
                        System.out.println(user);
                       
                        pr.println(user);pr.flush();
                      // pr.println(pass);
                        //pr.flush();
                      //String get=br.readLine();System.out.println("received : "+get);
                       
                       
                       
		}
		catch(Exception e)
		{
			System.err.println("Problem in connecting with the server. Exiting main.");
			System.exit(1);
		}
        
    }//GEN-LAST:event_jButton2ActionPerformed
public static DefaultListModel m=new DefaultListModel();
public static DefaultListModel online=new DefaultListModel();
    public static void add_to_all_list(String s)
{
    String tems=s.replaceFirst("All_", "");
    
    m.addElement(tems);
    jList1.setModel(m);
}
    public static DefaultListModel f=new DefaultListModel();
    public static void add_to_friend_list(String m)
    {
        String tems=m.replaceFirst("Friends_", "");
        f.addElement(tems);
        jList2.setModel(f);
    }
    public static DefaultListModel P=new DefaultListModel();
    public static void  add_to_pending_list(String s)
    {
        String tems=s.replaceFirst("Pending_", "");
        P.addElement(tems);
        jList4.setModel(P);
    }
    public static void add_to_online(String s)
    {
        String tems=s.replaceFirst("newonline_", "");
        System.out.println("online "+tems);
        online.addElement(tems);
        jList3.setModel(online);
    }
    public static void Remove_from_online(String s)
    {
        String tems=s.replaceFirst("leaving_", "");
        int len=online.getSize();
        for(int i=0;i<len;i++)
        {
            if(online.elementAt(i).equals(tems))
            {
                online.remove(i);break;
            }
        }
        jList3.setModel(online);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        String lel=To.getText().trim();
        String siko=SendMessage.getText().trim();
        if(lel.equals("")|| siko.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Empty fields");
        }
        else 
        {
                    String some="To_"+To.getText()+"_";
        some+=SendMessage.getText();
        pr.println(some);pr.flush();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jList1.getSelectedIndex()!=-1)
        {
        String item=jList1.getSelectedValue();
        item="req_"+item;
        System.out.println(item);
        pr.println(item);pr.flush();
        System.out.println(item+" done");
                // TODO add your handling code here:
        }
        else JOptionPane.showMessageDialog(null, "Nothing is selected");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            int index=jList4.getSelectedIndex();
            System.out.println(index);
            if(index!=-1)
            {
                DefaultListModel model=(DefaultListModel)jList4.getModel();
                String item =jList4.getSelectedValue();
                f.addElement(item);
               // online.addElement(item);
                jList2.setModel(f);
               // jList3.setModel(online);
                item="AcceptedRequest_"+item;
                pr.println(item);pr.flush();
                model.remove(index);
                 JOptionPane.showMessageDialog(null, "Request Accepted");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Nothing is selected");
            }
       // System.out.println(model.getElementAt(index));   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         String Reciever=To.getText().trim();
        String file_name=SendMessage.getText().trim();
        if(Reciever.equals("")||file_name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Empty fields");
        }
        else
        {
        pr.println("SendFile_"+file_name+"_"+Reciever);pr.flush();
        try{
                            File file = new File(file_name);
                            FileInputStream fis = new FileInputStream(file);
                            BufferedInputStream bis = new BufferedInputStream(fis);
                            OutputStream os = s.getOutputStream();
                            byte[] contents;
                            long fileLength = file.length();
                            long current = 0;

                            long start = System.nanoTime();
                            //delay(100000);
                            while (current != fileLength) {
                                int size = 10000;
                                byte mark;
                                if (fileLength - current > size) {
                                    current += size;
                                    mark=1;
                                } else {
                                    size = (int) (fileLength - current);
                                    current = fileLength;
                                    mark=0;
                                }
                                contents = new byte[size+1];
                                bis.read(contents, 0, size);
                                contents[size]=mark;
                                os.write(contents);
                                System.out.println("Sending file ... " + (current * 100) / fileLength + "% complete!");
                            }

                            os.flush();
                            JOptionPane.showMessageDialog(null,"File sent successfully!");
                            
                        } catch (Exception e) {
                            e.printStackTrace();
                            System.err.println("Could not transfer file.");
                        }  
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotherFrame().setVisible(true);
            }
        });
        try{
            
                       /* s = new Socket("localhost", 5556);
			br = new BufferedReader(new InputStreamReader(s.getInputStream()));
                        pr = new PrintWriter(s.getOutputStream());*/	
                      
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        while(true )
        {
            try{
			//pr = new PrintWriter(s.getOutputStream());			
                       // */
                        s = new Socket("localhost", 5556);
			br = new BufferedReader(new InputStreamReader(s.getInputStream()));
                        pr = new PrintWriter(s.getOutputStream());
                       if(br!=null)
                       {
                         String se=br.readLine();
                        System.out.println("in main "+se);
                        if(se.equals("ok"))
                        {
                            loginPage.setVisible(false);
                            Profile.setVisible(true);
                       
                           break;
                        }
                        else
                        {
                            //System.out.println(get);
                            JOptionPane.showMessageDialog(null,"username or password incorrect");
                        }
                       }
            
           
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        while(true)
        {
            try{
            String some=br.readLine();
            if(some.startsWith("All"))
            {
                add_to_all_list(some);
            }
            else if(some.startsWith("offlinemsg_"))
            {
                String off=some.replaceFirst("offlinemsg_", "");
                TextArea.setText(TextArea.getText()+"\n"+off);
            }
            else if(some.startsWith("Friends"))
            {
                System.out.println(some);
                add_to_friend_list(some);
            }
            else if(some.startsWith("Pending"))
            {
                add_to_pending_list(some);
            }
            else if(some.startsWith("newonline_"))
            {
                add_to_online(some);
            }
            else if(some.startsWith("leaving_"))
            {
                Remove_from_online(some);
            }
            else if(some.startsWith("msg"))
            {
                System.out.println(some);
                String []parts=some.split("_");
                System.out.println(parts[0]);
                System.out.println(parts[1]);
                TextArea.setText(TextArea.getText()+"\n"+parts[1]+" : "+parts[2]);
            }
            else if(some.startsWith("Not_friend_"))
            {
                JOptionPane.showMessageDialog(null, "Can not send to unknown people");
            }
            else if(some.startsWith("SuccessfulRequest"))
            {
                JOptionPane.showMessageDialog(null, "Friend Request Sent");
            }
            else if (some.startsWith("failed"))
            {
                JOptionPane.showMessageDialog(null, "You have already sent request ");
            }
            else if(some.startsWith("Download"))
            {
                    try {
                    byte[] contents = new byte[10001];

                    FileOutputStream fos = new FileOutputStream("cat and chicken for client.jpg");
                    BufferedOutputStream bos = new BufferedOutputStream(fos);
                    InputStream is = s.getInputStream();

                    int bytesRead = 0;

                    while ((bytesRead = is.read(contents)) != -1) {
                        bos.write(contents, 0, bytesRead-1);
                        byte mark=contents[bytesRead-1];
                        if(mark==0)
                            break;
                        //System.out.println("bos is busy , mark = "+mark);
                    }

                    bos.flush();
                    //System.out.println("bos flushed");
                } catch (Exception e) {
                    e.printStackTrace();
                    System.err.println("Could not transfer file.");
                }
            }
            System.out.println("success "+some);
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PassWord;
    public static javax.swing.JPanel Profile;
    private javax.swing.JTextArea SendMessage;
    public static javax.swing.JTextArea TextArea;
    private javax.swing.JTextField To;
    private javax.swing.JTextField UserName;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JList<String> jList1;
    public static javax.swing.JList<String> jList2;
    public static javax.swing.JList<String> jList3;
    public static javax.swing.JList<String> jList4;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public static javax.swing.JPanel loginPage;
    // End of variables declaration//GEN-END:variables
}
